---
title: "Getting data from the web"
output: html_document
date: "2025-10-09"
---

```{r setup, include = FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Load important packages

```{r}
library(rvest)
library(httr)
```

Import NDSUH data from the web

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```


This is an easy case

```{r}
ndsuh_df = 
  drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```


Now pull out elements

```{r}
title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)
```

## API.

Get data on API:

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```

Access BRFSS

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/api/v3/views/acme-vg9e/query.csv",
      query = list("app_token" = "h8ym4QiQDFerUXPrQwcA4VeP7")) |> 
  content("parsed")
```


Look at Pokemon data

```{r}
poke = 
  GET("https://pokeapi.co/api/v2/pokemon/1") |> 
  content()
```

