---
title: "Strings and factors"
output: github_document
date: "2025-10-09"
---

```{r setup, include = FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Load important packages

```{r}
library(rvest)
library(p8105.datasets)
```


## Mostly use string vectors

```{r}
string_vector = c("my", "name", "is", "jeff")

str_detect(string_vector, "jeff")
str_detect(string_vector, "Jeff") # case sensitive
str_detect(string_vector, "e")

str_replace(string_vector, "jeff", "Jeff")
str_replace(string_vector, "e", "E")

str_replace(string_vector, "e", "")

str_remove(string_vector, "e")
```

copied(from p8105.com)

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") # find at the start of string
str_detect(string_vec, "i think$") # find at the end of string

str_remove(string_vec, "i think$")
```


Pumpkin themed example

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "pumpkin")
str_detect(string_vec, "Pumpkin")

str_detect(string_vec, "[Pp]umpkin") # everything in the bracket is what we want

```

Let's more complicated:

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9]")
str_detect(string_vec, "[0-9][A-Z]")
str_detect(string_vec, "[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.1") # . means everything
str_detect(string_vec, "7\\.1") # find special characters
```

## Factors

```{r}
vec_sex = factor(c("male", "male", "female", "female")) # alphabetical order
vec_sex

as.numeric(vec_sex)

vec_sex = fct_inorder(vec_sex) # what comes first is first
vec_sex
```


## Revisit NDSUH

Import NDSUH data from the web

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(nsduh_url)
```


This is an easy case

```{r}
ndsuh_df = 
  drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
```


Now do the tidying...

```{r}
marj_df = 
  ndsuh_df |> 
  select(-contains("P Value")) |> 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) |> 
  separate(age_year, into = c("age", "year"), sep = "\\(") |> 
  mutate(
    year = str_remove(year, "\\)"),
    percent = str_remove(percent, "[a-c]$"),
    percent = as.numeric(percent)
  ) |> 
  filter(
    !(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West"))
  )
```

Let's make a plot:

```{r}
marj_df |> 
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


## Restaurant inspections
```{r}
data("rest_inspec")
```

```{r}
rest_inspec |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```


Update the dataset

```{r}
rest_inspec =
  rest_inspec|> 
  filter(grade %in% c("A", "B", "C"), boro != 0)
```

Look for pizza places:

```{r}
rest_inspec |> 
  filter(str_detect(dba, "Pizza")) |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```


```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  group_by(boro, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

Let's make a plot:

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

This does not work as intended:
```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(boro = fct_infreq(boro),
         boro = str_replace(boro, "Manhattan", "The City")) |> # goes back to alphabetic order
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

This works:

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(boro = fct_infreq(boro),
         boro = fct_recode(boro, "The City" ="Manhattan")) |> # Still remains the order, only change label
  ggplot(aes(x = boro, fill = grade)) + 
  geom_bar()
```

